package com.Lab4.ProductManagementSystem.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;

@Data
@NoArgsConstructor
@AllArgsConstructor

public class ProductDTO {
    private Long id;
    private String name;
    private double price;
    private String categoryName;// Assuming categoryId is a Long representing the ID of the category

    // Getters and setters (generated by lombok)
}
